### ISSUE TITLE
Visualização de botões laterais no mobile

### ISSUE THREAD

**Issue by AndersonGuerra** [AndersonGuerra/home_unifap#2]
É preciso fazer a visualização dos botões laterais no mobile se tornar mais responsiva, no momento atual ela 11 botões seguidos que ocupam toda a tela.
![botoeslaterais](https://user-images.githubusercontent.com/20675273/36731096-6406971e-1ba8-11e8-934b-a7e34e2448ae.PNG)

**Comment by mateusdalmeida** [comment]
Problema resolvido com o commit 43583bfe.
